### ISSUE TITLE
data files missing in the directory data

### ISSUE THREAD

**Issue by dliu201304** [jlduan/Reprogram-Seq#1]
Subdirectory "epicardial_10f_d7" and "epicardial_3f_d7" and related rds files are not found in the current edition under the directory "data/10x" in this project, would you please update these files?

**Comment by yuqiyuqitan** [comment]
I would be interested in those two files if you dont mind sharing them. thanks!

**Comment by jlduan** [comment]
Thank you for your interest in our data. I have updated the directories, and the large file (exceeding 100 Mb) can be downloaded [here](https://www.dropbox.com/s/oggve4qm3kkf7rc/cell_dataset_lowerDetectionLimit0.5_DDRTree_dim2_reverse.rds).
